// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiusubgfvxbfunrqmcvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpdXN1YmdmdnhiZnVucnFtY3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzUzMTUsImV4cCI6MjA2ODUxMTMxNX0.R1ShfF5vrCvkNhfXrxVm1xcD_uViXigvGCYjshgNff0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});